version: '3.8'

services:
  app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/e_commerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      CLOUDINARY_CLOUD_NAME: dxkofldog
      CLOUDINARY_API_KEY: 446982999267719
      CLOUDINARY_API_SECRET: fxS1jUxd40phjXxLNjcyVxQ3mAQ
    networks:
      - ecommerce-network

  db:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  postgres_data:
