spring:
  application:
    name: BackendDeveloperTaskForStartUp
  datasource:
    url: jdbc:postgresql://db:5432/e_commerce
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
